//! Embed every `data/models/*.json` into the binary at compile time.
//!
//! The files stay the source of truth — a contributor adds one JSON file and
//! opens a PR, with no Rust to touch and no merge conflict against a shared
//! list. Globbing here rather than maintaining a hand-written `include_str!`
//! array is what makes that true.
//!
//! Embedding (rather than reading at runtime) keeps the binary self-contained
//! and offline-capable, which matters for the users this project targets.

use std::path::PathBuf;

fn main() {
    // Build scripts run with the package root as the working directory.
    let dir = PathBuf::from("data/models");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    // Sorted so the generated file is byte-identical across machines, which
    // keeps builds reproducible.
    files.sort();

    let mut out = String::from(
        "/// Catalog files embedded at build time. Generated by build.rs.\n\
         pub static EMBEDDED: &[&str] = &[\n",
    );
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let abs = std::fs::canonicalize(path)
            .unwrap_or_else(|e| panic!("cannot resolve {}: {e}", path.display()));
        out.push_str(&format!("    include_str!(r\"{}\"),\n", abs.display()));
    }
    out.push_str("];\n");

    // The calibration dataset, both tiers. Embedded rather than read at
    // runtime for the same reason as the catalog: an installed user has no
    // repository, and a binary that cannot see the dataset predicts from priors
    // while the README quotes an accuracy figure computed from records it never
    // loaded.
    let calib = PathBuf::from("data/calibration");
    let community = calib.join("community");
    println!("cargo:rerun-if-changed={}", calib.display());
    println!("cargo:rerun-if-changed={}", community.display());
    let mut records: Vec<PathBuf> = vec![calib.join("gate.jsonl")];
    let mut merged: Vec<PathBuf> = std::fs::read_dir(&community)
        .into_iter()
        .flatten()
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "jsonl"))
        .collect();
    // Sorted for the same reason the catalog is: a byte-identical generated
    // file across machines is what keeps builds reproducible.
    merged.sort();
    records.extend(merged);

    out.push_str(
        "\n/// Calibration records embedded at build time. Generated by build.rs.\n\
         pub static EMBEDDED_CALIBRATION: &[&str] = &[\n",
    );
    for path in &records {
        if !path.is_file() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let abs = std::fs::canonicalize(path)
            .unwrap_or_else(|e| panic!("cannot resolve {}: {e}", path.display()));
        out.push_str(&format!("    include_str!(r\"{}\"),\n", abs.display()));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("catalog_embedded.rs");
    std::fs::write(&dest, out).expect("write generated catalog");
}
